proxy:
  host: '0.0.0.0'
  port: 9292
  daemonize: true
  timeout: 15
  output: /dev/null
# pid: 'log/kusabana.pid'
es:
  remotes:
    - path: '/hoge'
      host: 'hoge.com'
      port: 9201
    - path: '/fuga'
      host: 'fuga.com'
      port: 9200
# output:
#   index: 'kusabana-log-1'
#   hosts:
#   - host: 'localhost'
#     port: 9200
cache:
  url: 'localhost:11211'
  key_prefix: ''
